import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuIndicator,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  NavigationMenuViewport,
} from "@/components/ui/navigation-menu"
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      > 
        <NavigationMenu className="w-full [&>div]:!static">
          <NavigationMenuList className="justify-between min-w-full [&>div]:!static">
            
            
            <NavigationMenuItem>
              <NavigationMenuLink>
                lkasjl  
              </NavigationMenuLink>
            </NavigationMenuItem>

            <NavigationMenuItem>
              kjlsj
            </NavigationMenuItem>

            <NavigationMenuItem>
              <NavigationMenuLink>
                lakdj
              </NavigationMenuLink>
            </NavigationMenuItem>

            <NavigationMenuItem>
              <NavigationMenuLink>
                lasdkj
              </NavigationMenuLink>
            </NavigationMenuItem>  

          </NavigationMenuList> 
        </NavigationMenu> 
        {children}
      </body>
    </html>
  );
}
